---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: tws
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-e2e1b489
  image_type: t1.micro
  image_id: ami-def89fb7
  security_groups:
  - tws_production_default
  - tws_production_web
  - tws_production_web_tools
  - tws_production_tws
  - tws_production_app
  - tws_production_unicorn
  - tws_production_nginx
  - tws_production_collectd
  - tws_production_common
  - tws_production_monit
  - tws_production_examples
  - tws_production_graphite_server
  - tws_production_graphite_web
  - tws_production_mongodb
  - tws_production_db
  external_host: ec2-75-101-253-83.compute-1.amazonaws.com
  external_ip: 75.101.253.83
  internal_host: ip-10-164-102-116.ec2.internal
  internal_ip: 10.164.102.116
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
